# 登陆
POST {{baseUrl}}/login
Content-Type: application/json

{"email" : "jiesoul@gmail.com", "password" : "12345678" }

###

# 登出
POST {{baseUrl}}/logout
Content-Type: application/json

{"user_id" : 1, "token" : "string"}

###

# 用户
# 修改密码
PATCH {{baseUrl}}/users/1/password
Content-Type: application/json

{"oldPassword" :  "123456789", "newPassword" :  "12345678", "confirmPassword" : "12345678"}

###

# 修改个人信息
PATCH {{baseUrl}}/users/1/profile
Content-type: application/json

{ "username" : "ss" }

###

# 全部用户
GET {{baseUrl}}/users
Accept: application/json

###


# api-keys
GET {{baseUrl}}/api-keys/gen
Accept: application/json

###

POST {{baseUrl}}/api-keys
Content-Type: application/json

{"app_name":  "web","create_by": 1, "token":  "i/ByCooZNZeVlPFfwtJ+KYKIh+8jhlWs6+5yyu9NexcIWD5KYjsUgy/EG4tr7KOAvOGK8WsXEBCYjbESp14k+A=="}

###

DELETE {{baseUrl}}/2

###

# 数据字典
# 全部数据
GET {{baseUrl}}/data-dics
Accept: application/json

###

