

# 登陆
POST {{baseUrl}}/login
Content-Type: application/json

{"email" : "jiesoul@gmail.com", "password" : "123456789" }

###

# 登出
POST {{baseUrl}}/logout
Content-Type: application/json

{"user_id" : 1, "token" : "6kpLKukQIAUJCJbvnAa5hwNopVlGzYxSocqaweYl4Ec="}

###

# 用户
# 修改密码
PATCH {{baseUrl}}/users/1/password
Content-Type: application/json
Authorization: Token 6kpLKukQIAUJCJbvnAa5hwNopVlGzYxSocqaweYl4Ec=

{"oldPassword" :  "12345678", "newPassword" :  "123456789", "confirmPassword" : "123456789"}

###

# 修改个人信息
PATCH {{baseUrl}}/users/1/profile
Content-type: application/json
Authorization: Token 6kpLKukQIAUJCJbvnAa5hwNopVlGzYxSocqaweYl4Ec=

{ "username" : "ss" }

###

# 全部用户
GET {{baseUrl}}/users
Accept: application/json
Authorization: {{token}}

###


# app-keys
GET {{baseUrl}}/app-keys/gen
Accept: application/json
Authorization: {{token}}

###

POST {{baseUrl}}/app-keys
Content-Type: application/json
Authorization: {{token}}

{"app_name":  "web","create_by": 1, "token":  "ty57zxCEOc6KQeEcAz6PZcb3FneD2p7ANrsm0rmZID4="}

###

DELETE {{baseUrl}}/app-keys/1
Content-Type: application/json
Authorization: {{token}}

###


GET {{baseUrl}}/app-keys?page=1&app_name=ff
Accept: application/json
Authorization: {{token}}

###

# 数据字典
# 全部数据
GET {{baseUrl}}/data-dics
Accept: application/json
Authorization: {{token}}

###

GET {{baseUrl}}/data-dics/10
Accept: application/json
Authorization: {{token}}

###

GET {{baseUrl}}/data-dics/pid/0
Accept: application/json
Authorization: {{token}}

###

POST {{baseUrl}}/data-dics
Content-Type: application/json
Authorization: {{token}}

{"id": "99", "name" :  "test" ,"pid" :  "0", "create_by" :  1, "update_by" : 1}

###

PATCH {{baseUrl}}/data-dics
Content-Type: application/json
Authorization: {{token}}

{"id": "99", "name" :  "test-patch", "note": "" ,"pid" :  "0", "update_by" : 1}

###

DELETE {{baseUrl}}/data-dics/99
Content-Type: application/json
Authorization: {{token}}

###

# 系列

GET {{baseUrl}}/serials
Accept: application/json
Authorization: {{token}}

###

