# 配置文件版本
version: '3'

# 服务
services:
  # api
  api:
    image: api:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: jdbc:postgresql://172.17.0.1/soul_talk?user=jiesoul&password=soul1982

  # admin
  admin:
    depends_on:
      - api
    image: admin:latest
    ports:
      - "8081:80"

  # home

#存储
volumes:
  db-data: