version: '3'

services:
  db:
    image: postgres:latest
    container_name: pg-docker
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: jiesoul
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: soul_talk

  soul-talk:
    container_name: soul-talk
    depends_on:
      - db
    image: jiesoul/soul-talk:latest
    ports:
      - "3000:3000"
    restart: always

volumes:
  db-data: