version: '3'

services:
  db:
    image: postgres:latest
    container_name: pg-docker
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: jiesoul
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: soul_talk

  soul-talk:
    container_name: soul-talk
    depends_on:
      - db
    image: jiesoul/soul-talk:0.1.0
    ports:
      - "3000:3000"
    restart: always
    environment:
      DATABASE_URL: jdbc:postgresql://localhost:5432/soul_talk?user=jiesoul&password=12345678

volumes:
  db-data: