# 配置文件版本
version: '3'

# 服务
services:
  # 应用
  server:
    image: jiesoul/soul-talk:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: jdbc:postgresql://db/soul_talk?user=jiesoul&password=12345678

  # 后台
  client-back:

#存储
volumes:
  db-data: